default: &default
  adapter: mysql2
  pool: 5
  read_timeout: 10

development:
  <<: *default
  database: gjcase_development

test:
  <<: *default
  database: gjcase_test

production:
  <<: *default
  database: gjcase_production
