# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80171f75a6f8326d10d41d3cd0f1e3b18d1fc7099e9cd038897314da09b092e175f13e958c82b89c982ba27a619a564feb0932ecea37496509a68b1d725d361f
  camo: <%= ENV['GJCASE_CAMO_URL'] %>
  camo_key: <%= ENV['GJCASE_CAMO_KEY'] %>
  storage_url: <%= ENV['GJCASE_STORAGE'] %>

test:
  secret_key_base: a73b64b4795e5500acc39feaae2af5978190c4b2acdd4f4e24c24a254ce25b75ea2d2cbcd20da0ed604aafbad2a70098a3bbfc821e4d54b0f34b706464410908
  camo:
  camo_key:
  storage_url:

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  camo: <%= ENV['GJCASE_CAMO_URL'] %>
  camo_key: <%= ENV['GJCASE_CAMO_KEY'] %>
  storage_url: <%= ENV['GJCASE_STORAGE'] %>
